apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ymxn
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/mdsaud-tenant/my-default-app/devfile-sample-ymxn@sha256:cc506c429f3fb6a71f799c3ab5ef0972db354ca45793ec1c04fc5d1fda78f8ff
        name: my-nodejs
        resources: {}
status: {}
