apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: react-cards-demo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: react-cards-demo
    app.kubernetes.io/part-of: my-default-app
  name: react-cards-demo
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: react-cards-demo
status:
  loadBalancer: {}
