apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: my-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: my-component
    app.kubernetes.io/part-of: my-default-app
  name: my-component
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: my-component
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: my-component
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/mdsaud-tenant/my-default-app/my-component@sha256:5035a93b2616ebc4b850d2aa47cfc4b1699cadc61736178bcdc386c3c4c9d521
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
